version: '3.8'

services:
  nginx:
    container_name: nginx

    build: ./nginx
    ports:
      - "8090:8090"
    # volumes:
    #   - ./nginx:/etc/nginx
    #   - ./threads:/app/threads
    depends_on:
      - django_threads

  postgres:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_USER=root
      - POSTGRES_DB=threads

  django_threads:
    container_name: django_threads
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./threads/Dockerfile
    #command: gunicorn ./threads/threads/wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    restart: always
    stdin_open: true
    tty: true

  additional_server:
    container_name: additional_server
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./threads/Dockerfile
    #command: gunicorn ./threads/threads/wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    restart: always
    stdin_open: true
    tty: true


networks:
  app-tier:
    driver: bridge